repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
        exclude: ^examples/
      - id: terraform_validate
        exclude: ^examples/
      - id: terraform_docs
        exclude: ^examples/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]  # Optionally only show errors and warnings
